name: Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: root
          mysql password: password
          
      - name: Dotenv Action
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .env-template
          export-variables: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
